---
Parameters:
  CodeCommitRepoName:
    Type: String
  CodeBuildServiceRole:
    Type: String
  CodePipelineServiceRole:
    Type: String
  CloudformationServiceRole:
    Type: String
Resources:
    S3BucketArtifactStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: artifactstore-bucket-ahmad-4
        AccessControl: Private
    codebuild:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: codebuild-ahmad-4
        ServiceRole: 
          Ref: CodeBuildServiceRole
        Artifacts:
          Type: no_artifacts
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        Source:
          Location: 
            Ref: CodeCommitRepoName
          Type: CODECOMMIT
        SourceVersion: refs/heads/master
        TimeoutInMinutes: 10
    codepipeline:
      Type: AWS::CodePipeline::Pipeline 
      Properties: 
        Name: codepipeline-ahmad-4
        RoleArn: 
          Ref: CodePipelineServiceRole
        Stages: 
          - 
            Name: Source
            Actions: 
              - 
                Name: Source
                ActionTypeId: 
                  Category: Source 
                  Owner: AWS 
                  Version: 1 
                  Provider: CodeCommit
                OutputArtifacts: 
                  - 
                    Name: SourceArtifact
                Configuration: 
                  RepositoryName: codecommit-repo-ahmad
                  BranchName: master
                RunOrder: 1 
          - 
            Name: Build
            Actions: 
              - 
                Name: Build
                InputArtifacts: 
                  -
                    Name: SourceArtifact
                ActionTypeId: 
                  Category: Build
                  Owner: AWS 
                  Version: 1 
                  Provider: CodeBuild
                OutputArtifacts: 
                  - 
                    Name: BuildArtifact
                Configuration: 
                  ProjectName: 
                    Ref: codebuild
                RunOrder: 1
          -
            Name: CreateChangeSet
            Actions: 
              - 
                Name: CreateChangeSet
                InputArtifacts: 
                  -
                    Name: BuildArtifact
                ActionTypeId: 
                  Category: Deploy 
                  Owner: AWS 
                  Version: 1 
                  Provider: CloudFormation
                Configuration: 
                  ActionMode: CHANGE_SET_REPLACE
                  StackName: s3bucket-stack-ahmad
                  ChangeSetName: s3bucket-stack-changeset
                  RoleArn: 
                    Ref: CloudformationServiceRole
                  TemplatePath: BuildArtifact::packaged_template.yaml
                RunOrder: 1 
          -
            Name: ExecuteChangeSet
            Actions: 
              - 
                Name: ExecuteChangeSet 
                ActionTypeId: 
                  Category: Deploy 
                  Owner: AWS 
                  Version: 1 
                  Provider: CloudFormation
                Configuration: 
                  ActionMode: CHANGE_SET_EXECUTE
                  StackName: s3bucket-stack-ahmad
                  ChangeSetName: s3bucket-stack-changeset
                  RoleArn: 
                    Ref: CloudformationServiceRole
                RunOrder: 1 
        ArtifactStore: 
          Type: S3 
          Location:
            Ref: S3BucketArtifactStore